# -*- coding: utf-8 -*-
"""AnimeRunTesting.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LGUVm90hQdzjAlO4nK54rkqjvcsSYy7B
"""

# Commented out IPython magic to ensure Python compatibility.
import os, sys
from google.colab import drive
drive.mount('/content/drive')
nb_path = '/content/notebooks'
os.symlink('/content/drive/My Drive/Colab Notebooks', nb_path)
sys.path.insert(0,nb_path)
# %cd drive/MyDrive

!pip3 install torch-scatter AnimeRun/torch_scatter-2.1.0+pt113cu116-cp39-cp39-linux_x86_64.whl

!pip3 install pyyaml==5.4.1

# Commented out IPython magic to ensure Python compatibility.
# %cd drive/MyDrive

!python -u AnimeRun/segmat/main.py --config AnimeRun/segmat/configs/superglue_softmax_anime_contour.yaml --train

!python -u AnimeRun/segmat/main.py --config AnimeRun/segmat/configs/superglue_softmax_anime_contour.yaml --eval

"""# New Section"""